= Introduction
In computatinal data analysis, accurate data visualization is essential for analysing complex structures.
This is of particular interest in the field of fusion physics, where plasmas are confined by strong magnetic fields inside so called _tokamaks_.
These plasmas often form fine and intricate structures.
Clear and accurate visual representations of such structures play a crucial role in understanding and validating plasma phenomena.

To offer an alternative to the very costly experiments in tokamak fusion reactors, simulation software like the _Gyrokinetic Workshop_ (GKW) have been developed.
They make studying plasma behavior more accessible.
On the basis of GKW additional programs have been built to help evaluate and vizualize the data of the simulations. 
One such code is _ToPoVis_, which computes and visualizes poloidal cross sections of small scale turbulences in global tokamak simulations.
With it, its possible to easily identify how the plasma structure depends on plasma and geometry parameters.

However, due to computational constraints, simulations in GKW are usually done on a sparse grid. 
This poses challenges to visualization, which commonly depends on a high resolution for proper results.
In some low resolution runs numerical artifacts could be observed in plots generated by ToPoVis, as seen in @fig:intro:artifacts.
This thesis aims to tackle these issues by identifying the causes of these artifacts and exploring means to diminish them.

#include "../../figs/triangulation_artifacts/sparse/artefacts.typ"; <fig:intro:artifacts>

This thesis is organized as follows: First, all neccessary background information is supplied in Chapter @chap:background[]. 
This includes insight into the working details of GKW and ToPoVis as well as giving some technical concepts of interpolation and triangulation. 
Chapter @chap:improvement[] will then provide a detailed explanation of the improvements made to the ToPoVis code and how they are implemented.